### ISSUE TITLE
Parse the tasks as text and return objects

### ISSUE THREAD

**Issue by sinarf** [sinarf/todotxtclient#6]
Should respect the [Todo.txt format](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format)

**Comment by sinarf** [comment]
@bmedy if you can take a look at my first javascript code, it would be nice.

**Comment by bmedy** [comment]
Tips :
you can add `#!/usr/bin/env node` at start of file.
and allow execution mode on file
`$ chmod +x parseTask.js`

and then you can run your code with `./src/tasks/parseTask.js` 

Have good ;)

**Comment by sinarf** [comment]
Thanks great tip, I will use is for quick scripting 
I created an issue for the bug you found #7 ;)
